Lecture 3 add to cart
PlusqRED/phoneshop-servlet-api pull request #3
Opened 2019-03-30 22:25 UTC by PlusqRED

2019-03-31 09:45 UTC, vladkanash commented on src/main/java/com/es/phoneshop/model/product/cart/Cart.java
> +public class Cart {
Если экземпляры класса будут хранится в сессии, то его лучше сделать класс сериализуемым (чтобы дать возможность серверу кэшировать значение при включении/выключении)

2019-03-31 09:45 UTC, vladkanash commented on src/main/java/com/es/phoneshop/model/product/cart/Cart.java
> +    private List<CartItem> cartItems;
если значение поля не будет перезаписываться, то лучше сделать его final

2019-03-31 09:46 UTC, vladkanash commented on src/main/java/com/es/phoneshop/model/product/cart/HttpSessionCartService.java
> +    private static HttpSessionCartService INSTANCE;
это уже не константное поле, поэтому его название не должно быть в `UPPER_CASE`

2019-03-31 09:48 UTC, vladkanash commented on src/main/java/com/es/phoneshop/model/product/history/History.java
> +public class History {
Непонятно, зачем вообще этот класс нужен, он просто хранит в себе список, не добавляет никакой новой логики.

2019-03-31 09:50 UTC, vladkanash commented on src/main/java/com/es/phoneshop/model/product/history/HttpHistoryService.java
> +            req.getServletContext().setAttribute("history", customerHistory);
`ServletContext` - один общий объект для всего приложения, история просмотров должна быть своя для каждого пользователя (читай, для каждой сессии)

2019-03-31 09:51 UTC, vladkanash commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +                req.getServletContext().setAttribute("cart", customerCart);
снова `ServletContext `непонятно зачем. Корзина ведь тоже своя для каждого пользователя.

2019-03-31 09:54 UTC, vladkanash commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    private Error errorType = Error.UNKNOWN; // by default
Для чего нужно это поле? Мне кажется его можно заменить локальной переменной.
Нужно стремиться к тому, чтобы изменяемых полей было как можно меньше.

2019-03-31 09:56 UTC, vladkanash commented on src/main/java/com/es/phoneshop/web/helper/ProductDetailsErrorHandler.java
> +public class ProductDetailsErrorHandler implements ErrorHandler {
Странная архитектура, непонятное зачем нужен этот класс (и интерфейс). Если хочешь использовать enum чтобы хранить коды ошибок, почему бы не хранить там же и текст ошибки для каждого типа?

2019-03-31 10:03 UTC, vladkanash commented on src/main/webapp/WEB-INF/tags/master.tag
> +<tags:history dispayedNumber="3"/>
зачем нужен displayedNumber, если в HistoryService есть параметр, который контролирует размер сохраняемой истории?

2019-03-31 10:07 UTC, vladkanash requested changes
Баг №1: в корзину можно добавлять отрицательные значения продуктов
Баг №2: Зайди на http://localhost:8080/phoneshop-servlet-api/products/4, и добавь в корзину 3 раза по 5 продуктов. Результат: в корзине 15 продуктов, в то время как сток только 10

2019-03-31 10:11 UTC, vladkanash commented on src/test/java/com/es/phoneshop/model/product/history/HttpHistoryServiceTest.java
> +import org.junit.BeforeClass;
Убери неиспользуемые импорты (здесь и везде по проекту)

2019-04-01 07:52 UTC, PlusqRED commented on src/main/java/com/es/phoneshop/model/product/history/History.java
> +public class History {
но в Cart у нас та же логика, логическая часть архитектуры, есть же вероятность, что логика сможет добавится в эту часть (class History)

2019-04-01 08:02 UTC, PlusqRED commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    private Error errorType = Error.UNKNOWN; // by default
чтобы протестировать все возможные ошибки в `doPost`, а в `ProductDetailsPageServlet` есть геттер для `errorType`

2019-04-01 08:42 UTC, vladkanash commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    private Error errorType = Error.UNKNOWN; // by default
можно же тестировать результат работы метода
т.е если у тебя в ходе выполнения `doPost()` появится ошибка `OUT_OF_STOCK` - то должен быть редирект на урл с параметром `err=Error.OUT_OF_STOCK.errorCode`

2019-04-01 08:44 UTC, vladkanash commented on src/main/java/com/es/phoneshop/model/product/history/History.java
> +public class History {
Ну, в отличие от cart, я не думаю что тут можно что-то добавлять в будущем. `recentlyViewedProducts` это просто список продуктов, я считаю что незачем создавать доп. абстракцию над ним.

2019-04-01 08:44 UTC, PlusqRED commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    private Error errorType = Error.UNKNOWN; // by default
да, я думал об этом, просто не хотелось привязывать тесты к урлу

2019-04-01 11:15 UTC, merged